### ISSUE TITLE
Undefined index in ptrader.php

### ISSUE THREAD

**Issue by lbzt** [chrisiaut/phptrader#12]
the bot does not work propely i get the messages below:

PHP Warning:  file_get_contents(): Filename cannot be empty in /home/pi/phptrader/trader.php on line 631
PHP Notice:  Undefined index: btc in /home/pi/phptrader/trader.php on line 501
PHP Notice:  Undefined index: buyprice in /home/pi/phptrader/trader.php on line 503

**Comment by geek-at** [comment]
this is normal for the first run. It's because the script has not yet created the storage data (json file)

**Comment by lbzt** [comment]
Thanks but i am running the bot since Yesterday, i set chmod 777 to whole
directory what am i doing wrong?
Thanks prof. ;-)!!!!

Il 01 lug 2017 6:35 PM, "Christian Haschek" <notifications@github.com> ha
scritto:

**Comment by geek-at** [comment]
are you running the script from within the phptrader directory or did you just use "php /full/path/to/script.php"?

Are you one of my students? ;)

**Comment by lbzt** [comment]
Fronte the directory.

Il 01 lug 2017 6:56 PM, "Christian Haschek" <notifications@github.com> ha
scritto:

**Comment by lbzt** [comment]
Sorry, from the directory.
No, i am not One of You student (i Just Red your biography and i have Belen
very imptessed) but i would Be gladiatore to learn from a kind likes You!

Il 01 lug 2017 6:57 PM, "luca labozzetta" <magictouch74@gmail.com> ha
scritto:

**Comment by lbzt** [comment]
Sorry ( italian t9)!!!!

Il 01 lug 2017 7:00 PM, "luca labozzetta" <magictouch74@gmail.com> ha
scritto:

**Comment by duramato** [comment]
I'm also experiencing this @chrisiaut no matter which command i run,

```
php ~/phptrader/trader.php check
[i] Will use 'ETH Wallet' as crypto wallet :)
[i] Will use 'EUR Wallet' as currency wallet :)
[i] Will use EUR Wallet for payments

[i] Buy price: 170.33 EUR
[i] Sell price: 166.94 EUR
[i] Spot price: 168.63 EUR
[i] Difference buy/sell: 3.39 EUR

[i] Currently watching 1 transactions
[i] Buy price: 170.33 EUR
[i] Sell price: 166.94 EUR
[i] Spot price: 168.63 EUR
[i] Difference buy/sell: 3.39 EUR

PHP Notice:  Undefined index: btc in /root/phptrader/trader.php on line 506
PHP Notice:  Undefined index: buyprice in /root/phptrader/trader.php on line 508
 [#1] Watching SELL order for   5 EUR. Will sell when ETH price reaches 168 ETH.
````
```
php ~/phptrader/trader.php sell 5 168
[i] Will use 'ETH Wallet' as crypto wallet :)
[i] Will use 'EUR Wallet' as currency wallet :)
[i] Will use EUR Wallet for payments

[i] Buy price: 170.33 EUR
[i] Sell price: 166.94 EUR
[i] Spot price: 168.64 EUR
[i] Difference buy/sell: 3.39 EUR

[i] Adding SELL order for 5 EUR in ETH when price is >= 168 EUR
PHP Warning:  file_get_contents(): Filename cannot be empty in /root/phptrader/trader.php on line 636
```
