### ISSUE TITLE
Log Permissions Not Allowing Script To Run

### ISSUE THREAD

**Issue by DataBass504** [chrisiaut/phptrader#13]
I have installed the script on two separated devices, a rpi3 & a rpi0w. On the rpi3 I installed composer globally & on my rpi0w I installed composer locally, both devices are running into the same permissions error when trying to run the command ''./start.sh" in terminal. Here is the error:

./start.sh: line 2: /var/log/phptrader.log: Permission denied

Can someone please explain to me how to get past this error & fix the issue, thank you in advance.

**Comment by geek-at** [comment]
either start the script as root or with "sudo"
