### ISSUE TITLE
[ERR] Could not find your BTC Wallet. Do you have one on Coinbase?

### ISSUE THREAD

**Issue by dwongdev** [chrisiaut/phptrader#8]
Installed and redownload a couple of times. Not working.
Renewed my API keys as well. Both running latest version of PHP and composer too.
Installed on Ubuntu 16.04, Windows 8.1 and Ubuntu MATE (Raspberry Pi 3), no luck.

When trying to use command: php trader.php buy
 
Terminal Error: 
[i] Will use 'BTC Wallet' as crypto wallet :)
[ERR] Could not find your BTC Wallet. Do you have one on Coinbase?

**Comment by geek-at** [comment]
Alright it looks like you have chosen to use BTC as crypto AND payment wallet? This won't work, you need to choose either USD or EUR
